### ISSUE TITLE
Week-3 Issue with Amplify.Cofigure(params) - I'm using Amplify - v6

### ISSUE THREAD

**Issue by Abrish-Green** [Abrish-Green/aws-bootcamp-cruddur-2023#1]
Error in console
=============
Uncaught InvalidParameterException: Invalid config parameter.
    at parseAWSExports (http://localhost:3000/static/js/bundle.js:60249:11)
    at Object.configure (http://localhost:3000/static/js/bundle.js:61461:114)
    at ./src/App.js (http://localhost:3000/static/js/bundle.js:654:58)
    at options.factory (http://localhost:3000/static/js/bundle.js:70443:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:69867:33)
    at fn (http://localhost:3000/static/js/bundle.js:70100:21)
    at ./src/index.js (http://localhost:3000/static/js/bundle.js:3852:62)
    at options.factory (http://localhost:3000/static/js/bundle.js:70443:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:69867:33)
    at http://localhost:3000/static/js/bundle.js:71089:37
......

- I have face issue and I fixed it using ` AWS_PROJECT_REGION` to `aws_project_region` in the amplify.configure()

**Comment by Abrish-Green** [comment]
I have face issue and I fixed it using  AWS_PROJECT_REGION to aws_project_region in the amplify.configure()
